name:                gameboy
version:             0.1.0.0
github:              "kmtoki/gbe-hs"
license:             BSD3
author:              "kmtoki"
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gameboy#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- vector
- microlens-platform
- mtl
- regex-compat

library:
  source-dirs: src

default-extensions: 
- TemplateHaskell
- OverloadedStrings
- OverloadedLabels
- BinaryLiterals
- Strict
- StrictData
- RecordWildCards
- DuplicateRecordFields
- ScopedTypeVariables
#- RankNTypes
#- StandaloneDeriving
#- FlexibleInstances
#- TypeFamilies
#- GADTs
#- DataKinds
#- KindSignatures
#- FlexibleInstances
#- OverloadedRecordDot
- GeneralizedNewtypeDeriving
- DerivingVia
- MultiParamTypeClasses


executables:
  gameboy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameboy
    when:        
    - condition: false        
      other-modules: Paths_gameboy



tests:
  gameboy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameboy
    when:        
    - condition: false        
      other-modules: Paths_tests_gameboy
